version: '3'

services:
  redis-overcommit:
    build: https://github.com/bkuhl/redis-overcommit-on-host.git
    restart: 'no'
    privileged: true
    volumes:
     - /proc/sys/vm:/mnt/vm
  redis:
    image: redis:5
    restart: 'always'
    ports:  
     - "6378:6379"
    depends_on:
     - redis-overcommit`
  web:
    tty: true
    build: .
    depends_on: 
     - redis
    image: firstimg:firstpush
    #command: sh -c "python manage.py makemigrations && python manage.py migrate && python manage.py runserver"
    ports:
     - "5000:5000"
    links:
     - redis


#gunicorn --bind 0.0.0.0:5000 chat.asgi -w 4 -k uvicorn.workers.UvicornWorker