# Generated by Django 4.1.3 on 2022-12-24 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='user',
        ),
        migrations.AddField(
            model_name='room',
            name='lang',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
